// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL8bY1B6yfcIVIn4nyBH6COVYdRlswSjw',
    appId: '1:683371057873:web:a35c337b67088b09adebf0',
    messagingSenderId: '683371057873',
    projectId: 'step-counter-via',
    authDomain: 'step-counter-via.firebaseapp.com',
    storageBucket: 'step-counter-via.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZWQBW6ye-SsgN0wJmiiwSbw8FQh1UyJQ',
    appId: '1:683371057873:android:09cd7fdc5de45da3adebf0',
    messagingSenderId: '683371057873',
    projectId: 'step-counter-via',
    storageBucket: 'step-counter-via.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvlP5Geach2Ut8igGRlP7Vd9oRerQPG9g',
    appId: '1:683371057873:ios:c4cd7e9869da8054adebf0',
    messagingSenderId: '683371057873',
    projectId: 'step-counter-via',
    storageBucket: 'step-counter-via.appspot.com',
    iosBundleId: 'com.example.stepCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvlP5Geach2Ut8igGRlP7Vd9oRerQPG9g',
    appId: '1:683371057873:ios:021d42c7962a133eadebf0',
    messagingSenderId: '683371057873',
    projectId: 'step-counter-via',
    storageBucket: 'step-counter-via.appspot.com',
    iosBundleId: 'com.example.stepCounter.RunnerTests',
  );
}
